# Generated by Django 4.1.1 on 2022-10-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AlarmList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alarm_id", models.IntegerField()),
                ("caption", models.CharField(max_length=5000)),
                ("music", models.IntegerField()),
            ],
            options={"db_table": "alarmlist",},
        ),
        migrations.CreateModel(
            name="MusicList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("artist", models.CharField(max_length=100)),
                ("image_name", models.CharField(max_length=100)),
                ("mp3_name", models.CharField(max_length=100)),
                ("music_theme", models.CharField(max_length=100)),
            ],
            options={"db_table": "musiclist",},
        ),
        migrations.CreateModel(
            name="MusicTheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("theme_name", models.CharField(max_length=100)),
            ],
            options={"db_table": "musictheme",},
        ),
        migrations.CreateModel(
            name="TimeList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.IntegerField()),
                ("hour", models.IntegerField()),
                ("min", models.IntegerField()),
                ("alarm", models.IntegerField()),
            ],
            options={"db_table": "timelist",},
        ),
    ]
