# Generated by Django 4.1.1 on 2022-10-12 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="musiclist",
            name="image_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="musiclist",
            name="mp3_name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
