# Generated by Django 4.1 on 2022-10-13 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app", "0003_delete_alarmlist_delete_musiclist_delete_musictheme_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlarmList",
            fields=[
                ("alarm_id", models.IntegerField(primary_key=True, serialize=False)),
                ("caption", models.CharField(max_length=5000)),
            ],
            options={"db_table": "alarmlist",},
        ),
        migrations.CreateModel(
            name="MusicTheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("theme_name", models.CharField(max_length=100)),
            ],
            options={"db_table": "musictheme",},
        ),
        migrations.CreateModel(
            name="TimeList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.IntegerField()),
                ("hour", models.IntegerField()),
                ("min", models.IntegerField()),
                (
                    "alarm",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.alarmlist",
                    ),
                ),
            ],
            options={"db_table": "timelist",},
        ),
        migrations.CreateModel(
            name="MusicList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("artist", models.CharField(max_length=100)),
                ("image_name", models.CharField(max_length=100, null=True)),
                ("mp3_name", models.CharField(max_length=100, null=True)),
                (
                    "music_theme",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.musictheme",
                    ),
                ),
            ],
            options={"db_table": "musiclist",},
        ),
        migrations.AddField(
            model_name="alarmlist",
            name="music",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.musiclist",
            ),
        ),
    ]
