# Generated by Django 4.1 on 2022-10-13 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="musiclist", name="music_theme",),
        migrations.RemoveField(model_name="timelist", name="alarm",),
        migrations.DeleteModel(name="AlarmList",),
        migrations.DeleteModel(name="MusicList",),
        migrations.DeleteModel(name="MusicTheme",),
        migrations.DeleteModel(name="TimeList",),
    ]
