# Generated by Django 4.1.1 on 2022-10-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="alarmlist",
            name="specialnum",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
