# Generated by Django 4.1 on 2022-10-17 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="daylist", name="date", field=models.CharField(max_length=100),
        ),
    ]
